import { Icon } from '@iconify/react';
import Head from 'next/head';
import React, { useState } from 'react';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';
import ContactInfoWidget from '../components/Widget/ContactInfoWidget';
import Swal from 'sweetalert2';

export default function Contact() {
  const [formData, setFormData] = useState({
    fullName: '',
    email: '',
    mobile: '',
    message: '',
    service: '', // Added service field
  });

  const [loading, setLoading] = useState(false); // State variable for loading

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true); // Set loading to true when form is submitted

    try {
      const response = await fetch('/api/sendEmail', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
      if (response.ok) {
        Swal.fire('Success', 'Message sent successfully!', 'success');
        setFormData({
          fullName: '',
          email: '',
          mobile: '',
          message: '',
          service: '', // Reset service field after successful submission
        });
      } else {
        Swal.fire('Error', 'Failed to send message. Please try again later.', 'error');
      }
    } catch (error) {
      console.error('Error sending email:', error);
      Swal.fire('Error', 'An error occurred while sending the message.', 'error');
    } finally {
      setLoading(false); // Set loading back to false after form submission is complete
    }
  };

  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Contact Us"
          bgSrc="/images/contact_hero_bg.jpeg"
          pageLinkText="Contact"
        />
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-lg-6">
              <SectionHeading
                title="Shape Your Tomorrow <br/> Start a Conversation & Explore Packages"
                subtitle="Getting Touch"
              />
              <Spacing lg="55" md="30" />
              <ContactInfoWidget withIcon />
              <Spacing lg="0" md="50" />
            </Div>
            <Div className="col-lg-6">
              <form onSubmit={handleSubmit} className="row">
                <Div className="col-sm-6">
                  <label className="cs-primary_color">Full Name*</label>
                  <input
                    type="text"
                    className="cs-form_field"
                    name="fullName"
                    value={formData.fullName}
                    onChange={handleChange}
                    required
                  />
                  <Spacing lg="20" md="20" />
                </Div>
                <Div className="col-sm-6">
                  <label className="cs-primary_color">Email*</label>
                  <input
                    type="text"
                    className="cs-form_field"
                    name="email"
                    value={formData.email}
                    onChange={handleChange}
                    required
                  />
                  <Spacing lg="20" md="20" />
                </Div>
                <Div className="col-sm-6">
                  <label className="cs-primary_color">Mobile*</label>
                  <input
                    type="text"
                    className="cs-form_field"
                    name="mobile"
                    value={formData.mobile}
                    onChange={handleChange}
                    required
                  />
                  <Spacing lg="20" md="20" />
                </Div>
                <Div className="col-sm-6">
                  <label className="cs-primary_color">Service*</label>
                  <select
                    className="cs-form_field"
                    value={formData.service}
                    onChange={handleChange}
                    name="service"
                    required
                    style={{ backgroundColor: 'black', color: 'white' }} // Apply custom styles
                  >
                    <option value="">Choose a service</option>
                    <option value="Starter">Starter 200 DT/1 month</option>
                    <option value="Essential">Essential 500 DT/3 months</option>
                    <option value="Advanced">Advanced 900 DT/6 months</option>
                    <option value="Ultimate">Ultimate 1500 DT/1 year</option>
                  </select>
                  <Spacing lg="20" md="20" />
                </Div>
                <Div className="col-sm-12">
                  <label className="cs-primary_color">Message*</label>
                  <textarea
                    cols="30"
                    rows="7"
                    className="cs-form_field"
                    name="message"
                    value={formData.message}
                    onChange={handleChange}
                    required
                  ></textarea>
                  <Spacing lg="25" md="25" />
                </Div>
                <Div className="col-sm-12">
                  <button type="submit" className="cs-btn cs-style1" disabled={loading}>
                    {loading ? <span>Loading...</span> : <span>Send Message</span>}
                    <Icon icon="bi:arrow-right" />
                  </button>
                </Div>
              </form>
            </Div>
          </Div>
        </Div>
        <Spacing lg="150" md="80" />
        <Div className="cs-google_map">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6783640.384703555!2d4.260116614234153!3d33.88129805563389!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x125595448316a4e1%3A0x3a84333aaa019bef!2sTunisia!5e0!3m2!1sen!2sbd!4v1715538850554!5m2!1sen!2sbd"
            allowFullScreen
            title="Google Map"
          />
        </Div>
        <Spacing lg="50" md="40" />
      </Layout>
    </>
  );
}
